### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by PriyankaJain-1998** [namratesh/TableDetection#2]
Can you please tell from where did you get those weights from? file name "t3.h5" used in the final_deployment code.

**Comment by CarlosRCDev** [comment]
you can find the model in stream.py:
https://drive.google.com/file/d/17K_wZ1o2DVSdk0M7gOYBkJsbBsdH6rzj/view?usp=sharingt

**Comment by namratesh** [comment]
Hi Priyanka, 
After training the model, you can save you model in pickle file. Let me know , if you need mine one.
